---
title: "Scratch"
author: "Brody Kendall"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
library(tidyverse)
library(TmCalculator)
```


```{r}
# cycle3 <- read_csv("cycle3.txt")
cycle5 <- read_csv("cycle5.txt")


# dat <- cycle3
dat <- cycle5

free_energy <- read_csv("data/Created/kim_min_free_energy.csv")

free_energy <- free_energy[1:82368,]

dat <- dat %>%
  bind_cols(free_energy)

source("scripts/functions/sequence-functions.R")
```


```{r}
nucleotides <- c("A", "C", "G", "T")

dinucleotides <- gtools::permutations(n = 4, r = 2, v = nucleotides,
                                      repeats.allowed = TRUE) %>%
  apply(1, paste, collapse = "")

trinucleotides <- gtools::permutations(n = 4, r = 3, v = nucleotides,
                                       repeats.allowed = TRUE) %>%
  apply(1, paste, collapse = "")

tetranucleotides <- gtools::permutations(n = 4, r = 4, v = nucleotides,
                                         repeats.allowed = TRUE) %>%
  apply(1, paste, collapse = "")

pentanucleotides <- gtools::permutations(n = 4, r = 5, v = nucleotides,
                                         repeats.allowed = TRUE) %>%
  apply(1, paste, collapse = "")
```


```{r}
dat %>% map_df(~ sum(is.na(.x)))

dat <- dat %>%
  dplyr::select(x50mer = Sequence,
                C0,
                grna_energy, grna_scaffold_energy) %>%
  mutate(x41mer = substring(x50mer, 5, 45))
# 
# dat <- dat %>%
#   select(x50mer = Sequence,
#          C0)

dat_melting <- dat %>%
  group_by(1:n()) %>%
  transmute(tm1 = Tm_Wallace(x41mer)$Tm,
            tm2 = Tm_Wallace(substring(x41mer, 1, 4))$Tm,
            tm3 = Tm_Wallace(substring(x41mer, 5, 12))$Tm,
            tm4 = Tm_Wallace(substring(x41mer, 36, 40))$Tm) %>%
  ungroup() %>%
  select(-`1:n()`)
```

```{r}
sequence_1_df <- dat %>%
  pull(x50mer) %>%
  sequence_df()

sequence_2_df <- dat %>%
  pull(x50mer) %>%
  map(~unlist(strsplit(.x, ""))) %>%
  map(~splitWithOverlap(.x, 2, 1)) %>%
  map_depth(2, paste0, collapse = "") %>%
  map(unlist) %>%
  unlist() %>%
  {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
  data.frame(stringsAsFactors = FALSE)

sequence_3_df <- dat %>%
  pull(x50mer) %>%
  map(~unlist(strsplit(.x, ""))) %>%
  map(~splitWithOverlap(.x, 3, 2)) %>%
  map_depth(2, paste0, collapse = "") %>%
  map(unlist) %>%
  unlist() %>%
  {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
  data.frame(stringsAsFactors = FALSE)

sequence_4_df <- dat %>%
  pull(x50mer) %>%
  map(~unlist(strsplit(.x, ""))) %>%
  map(~splitWithOverlap(.x, 4, 3)) %>%
  map_depth(2, paste0, collapse = "") %>%
  map(unlist) %>%
  unlist() %>%
  {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
  data.frame(stringsAsFactors = FALSE)

sequence_5_df <- dat %>%
  pull(x50mer) %>%
  map(~unlist(strsplit(.x, ""))) %>%
  map(~splitWithOverlap(.x, 5, 4)) %>%
  map_depth(2, paste0, collapse = "") %>%
  map(unlist) %>%
  unlist() %>%
  {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
  data.frame(stringsAsFactors = FALSE)

for(i in 3:49) {
  assign(paste0("interaction_", i, "_df"), dat %>%
           pull(x50mer) %>%
           map(~unlist(strsplit(.x, ""))) %>%
           map(~splitWithOverlap2(.x, i+1, i)) %>%
           map_depth(2, paste0, collapse = "") %>%
           map(unlist) %>%
           unlist() %>%
           {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
           data.frame(stringsAsFactors = FALSE))
}

for(i in 3:47) {
  assign(paste0("di_interaction_", i, "_df"), dat %>%
           pull(x50mer) %>%
           map(~unlist(strsplit(.x, ""))) %>%
           map(~splitWithOverlap3(.x, i+1, i)) %>%
           map_depth(2, paste0, collapse = "") %>%
           map(unlist) %>%
           unlist() %>%
           {matrix(., nrow = nrow(dat), byrow = TRUE)} %>%
           data.frame(stringsAsFactors = FALSE))
}
```

```{r}
sequence_1_factor <- sequence_1_df %>%
  map_df(~ factor(.x, levels = c("A", "C", "G", "T"))) %>%
  as.data.frame() %>%
  rename_all(~paste0(.x, "mono"))

sequence_2_factor <- sequence_2_df %>%
  map_df(~ factor(.x, levels = dinucleotides)) %>%
  as.data.frame() %>%
  rename_all(~paste0(.x, "di")) %>%
  select(-X50di)

sequence_3_factor <- sequence_3_df %>%
  map_df(~ factor(.x, levels = trinucleotides)) %>%
  as.data.frame() %>%
  rename_all(~ paste0(.x, "tri")) %>%
  select(-X49tri, -X50tri)

sequence_4_factor <- sequence_4_df %>%
  map_df(~ factor(.x, levels = tetranucleotides)) %>%
  as.data.frame() %>%
  rename_all(~ paste0(.x, "tetra")) %>%
  select(-X48tetra, -X49tetra, -X50tetra)

sequence_5_factor <- sequence_5_df %>%
  map_df(~ factor(.x, levels = pentanucleotides)) %>%
  as.data.frame() %>%
  rename_all(~ paste0(.x, "penta")) %>%
  select(-X47penta, -X48penta, -X49penta, -X50penta)

factor_seq <- sequence_1_factor %>%
  bind_cols(sequence_2_factor, sequence_3_factor, sequence_4_factor, sequence_5_factor)

for(i in 3:49) {
  assign(paste0("interaction_", i, "_factor"), get(paste0("interaction_", i, "_df")) %>%
           map_df(~ factor(.x, levels = dinucleotides)) %>%
           as.data.frame() %>%
           rename_all(~paste0(.x, "int", i)))
}
interaction_49_factor <- interaction_49_factor %>%
  rename(X1int49 = .int49)

factor_int <- interaction_3_factor
for(i in 4:49) {
  factor_int <- factor_int %>%
    bind_cols(get(paste0("interaction_", i, "_factor")))
}


for(i in 3:47) {
  assign(paste0("di_interaction_", i, "_factor"), get(paste0("di_interaction_", i, "_df")) %>%
           map_df(~ factor(.x, levels = tetranucleotides)) %>%
           as.data.frame() %>%
           rename_all(~paste0(.x, "di_int", i)))
}
di_interaction_47_factor <- di_interaction_47_factor %>%
  rename(X1di_int47 = .di_int47)

factor_di_int <- di_interaction_3_factor
for(i in 4:47) {
  factor_di_int <- factor_di_int %>%
    bind_cols(get(paste0("di_interaction_", i, "_factor")))
}
```

```{r}
library(stringi)
```

```{r}
nc_1 <- nucleotides %>%
  map(~ str_count(dat$x50mer, .x)) %>%
  bind_cols()

nc_2 <- dinucleotides %>%
  map(~ str_count(dat$x50mer, .x)) %>%
  bind_cols()

nc_3 <- trinucleotides %>%
  map(~ str_count(dat$x50mer, .x)) %>%
  bind_cols()

colnames(nc_1) <- nucleotides
colnames(nc_2) <- dinucleotides
colnames(nc_3) <- trinucleotides

for(i in 3:49) {
  assign(paste0("nc_int", i), dinucleotides %>%
           map(~ stri_count(dat$x50mer, regex = paste0(substr(.x,1,1), 
                                                       paste0('.{', i-1, '}'), 
                                                       substr(.x,2,2)))) %>%
           bind_cols())
}

colnames(nc_int3) <- paste0(dinucleotides, "int3")
colnames(nc_int4) <- paste0(dinucleotides, "int4")
colnames(nc_int5) <- paste0(dinucleotides, "int5")
colnames(nc_int6) <- paste0(dinucleotides, "int6")
colnames(nc_int7) <- paste0(dinucleotides, "int7")
colnames(nc_int3) <- paste0(dinucleotides, "int8")
colnames(nc_int9) <- paste0(dinucleotides, "int9")
colnames(nc_int10) <- paste0(dinucleotides, "int10")
colnames(nc_int11) <- paste0(dinucleotides, "int11")
colnames(nc_int12) <- paste0(dinucleotides, "int12")
colnames(nc_int13) <- paste0(dinucleotides, "int13")
colnames(nc_int14) <- paste0(dinucleotides, "int14")
colnames(nc_int15) <- paste0(dinucleotides, "int15")
colnames(nc_int16) <- paste0(dinucleotides, "int16")
colnames(nc_int17) <- paste0(dinucleotides, "int17")
colnames(nc_int18) <- paste0(dinucleotides, "int18")
colnames(nc_int19) <- paste0(dinucleotides, "int19")
colnames(nc_int10) <- paste0(dinucleotides, "int20")
colnames(nc_int21) <- paste0(dinucleotides, "int21")
colnames(nc_int22) <- paste0(dinucleotides, "int22")
colnames(nc_int23) <- paste0(dinucleotides, "int23")
colnames(nc_int24) <- paste0(dinucleotides, "int24")
colnames(nc_int25) <- paste0(dinucleotides, "int25")
colnames(nc_int26) <- paste0(dinucleotides, "int26")
colnames(nc_int27) <- paste0(dinucleotides, "int27")
colnames(nc_int28) <- paste0(dinucleotides, "int28")
colnames(nc_int29) <- paste0(dinucleotides, "int29")
colnames(nc_int30) <- paste0(dinucleotides, "int30")
colnames(nc_int31) <- paste0(dinucleotides, "int31")
colnames(nc_int32) <- paste0(dinucleotides, "int32")
colnames(nc_int33) <- paste0(dinucleotides, "int33")
colnames(nc_int34) <- paste0(dinucleotides, "int34")
colnames(nc_int35) <- paste0(dinucleotides, "int35")
colnames(nc_int36) <- paste0(dinucleotides, "int36")
colnames(nc_int37) <- paste0(dinucleotides, "int37")
colnames(nc_int38) <- paste0(dinucleotides, "int38")
colnames(nc_int39) <- paste0(dinucleotides, "int39")
colnames(nc_int40) <- paste0(dinucleotides, "int40")
colnames(nc_int41) <- paste0(dinucleotides, "int41")
colnames(nc_int42) <- paste0(dinucleotides, "int42")
colnames(nc_int43) <- paste0(dinucleotides, "int43")
colnames(nc_int44) <- paste0(dinucleotides, "int44")
colnames(nc_int45) <- paste0(dinucleotides, "int45")
colnames(nc_int46) <- paste0(dinucleotides, "int46")
colnames(nc_int47) <- paste0(dinucleotides, "int47")
colnames(nc_int48) <- paste0(dinucleotides, "int48")
colnames(nc_int49) <- paste0(dinucleotides, "int49")

for(i in 3:47) {
  assign(paste0("nc_di_int", i), tetranucleotides %>%
           map(~ stri_count(dat$x50mer, regex = paste0(substr(.x,1,2), 
                                                       paste0('.{', i-1, '}'), 
                                                       substr(.x,3,4)))) %>%
           bind_cols())
}

colnames(nc_di_int3) <- paste0(tetranucleotides, "int3")
colnames(nc_di_int4) <- paste0(tetranucleotides, "int4")
colnames(nc_di_int5) <- paste0(tetranucleotides, "int5")
colnames(nc_di_int6) <- paste0(tetranucleotides, "int6")
colnames(nc_di_int7) <- paste0(tetranucleotides, "int7")
colnames(nc_di_int8) <- paste0(tetranucleotides, "int8")
colnames(nc_di_int9) <- paste0(tetranucleotides, "int9")
colnames(nc_di_int10) <- paste0(tetranucleotides, "int10")
colnames(nc_di_int11) <- paste0(tetranucleotides, "int11")
colnames(nc_di_int12) <- paste0(tetranucleotides, "int12")
colnames(nc_di_int13) <- paste0(tetranucleotides, "int13")
colnames(nc_di_int14) <- paste0(tetranucleotides, "int14")
colnames(nc_di_int15) <- paste0(tetranucleotides, "int15")
colnames(nc_di_int16) <- paste0(tetranucleotides, "int16")
colnames(nc_di_int17) <- paste0(tetranucleotides, "int17")
colnames(nc_di_int18) <- paste0(tetranucleotides, "int18")
colnames(nc_di_int19) <- paste0(tetranucleotides, "int19")
colnames(nc_di_int20) <- paste0(tetranucleotides, "int20")
colnames(nc_di_int21) <- paste0(tetranucleotides, "int21")
colnames(nc_di_int22) <- paste0(tetranucleotides, "int22")
colnames(nc_di_int23) <- paste0(tetranucleotides, "int23")
colnames(nc_di_int24) <- paste0(tetranucleotides, "int24")
colnames(nc_di_int25) <- paste0(tetranucleotides, "int25")
colnames(nc_di_int26) <- paste0(tetranucleotides, "int26")
colnames(nc_di_int27) <- paste0(tetranucleotides, "int27")
colnames(nc_di_int28) <- paste0(tetranucleotides, "int28")
colnames(nc_di_int29) <- paste0(tetranucleotides, "int29")
colnames(nc_di_int30) <- paste0(tetranucleotides, "int30")
colnames(nc_di_int31) <- paste0(tetranucleotides, "int31")
colnames(nc_di_int32) <- paste0(tetranucleotides, "int32")
colnames(nc_di_int33) <- paste0(tetranucleotides, "int33")
colnames(nc_di_int34) <- paste0(tetranucleotides, "int34")
colnames(nc_di_int35) <- paste0(tetranucleotides, "int35")
colnames(nc_di_int36) <- paste0(tetranucleotides, "int36")
colnames(nc_di_int37) <- paste0(tetranucleotides, "int37")
colnames(nc_di_int38) <- paste0(tetranucleotides, "int38")
colnames(nc_di_int39) <- paste0(tetranucleotides, "int39")
colnames(nc_di_int40) <- paste0(tetranucleotides, "int40")
colnames(nc_di_int41) <- paste0(tetranucleotides, "int41")
colnames(nc_di_int42) <- paste0(tetranucleotides, "int42")
colnames(nc_di_int43) <- paste0(tetranucleotides, "int43")
colnames(nc_di_int44) <- paste0(tetranucleotides, "int44")
colnames(nc_di_int45) <- paste0(tetranucleotides, "int45")
colnames(nc_di_int46) <- paste0(tetranucleotides, "int46")
colnames(nc_di_int47) <- paste0(tetranucleotides, "int47")

#GC count
gc_count <- nc_1 %>%
  transmute(gc_count = G + C)
```

```{r}
dat_seq <- factor_seq %>%
  bind_cols(nc_1,
            nc_2,
            nc_3,
            gc_count,
            dat)

dat <- dat %>%
  bind_cols(factor_seq,
            factor_int,
            factor_di_int,
            nc_1,
            nc_2,
            nc_3, 
            gc_count,
            dat_melting)

for(i in 3:49) {
  dat <- dat %>%
    bind_cols(get(paste0("nc_int", i)))
}

# for(i in 3:47) {
#   dat <- dat %>%
#     bind_cols(get(paste0("nc_di_int", i)))
# }

# for(i in 3:37) {
#   dat <- dat %>%
#     bind_cols(get(paste0("nc_di_int", i)))
# }

set.seed(50)

train_indices = sample(1:nrow(dat), nrow(dat)*.9, replace=FALSE)

dat_train = dat[train_indices,]
dat_test = dat[-train_indices,]
dat_seq = dat_seq[train_indices,]
dat = dat_train

saveRDS(dat, "data/Created/processed.rds")
saveRDS(dat_test, "data/Created/processed_test.rds")
saveRDS(dat_seq, "data/Created/processed_seq.rds")
```

05-data-split

```{r}
library(modelr)
```

```{r}
set.seed(50)

kfold_obj <- dat %>%
  crossv_kfold(10, id = "fold") %>%
  mutate(train = map(train, as.data.frame),
         test = map(test, as.data.frame))
```

06-markov-feature-comparisons

```{r}
source("scripts/functions/markov-functions.R")
library(markovchain)
```

```{r}
likelihood_ratio_outcomes <- list()

for(i in 1:3){
  
  #Calculate likelihood ratio using different quantile cutoffs for
  #low and high-efficiency sgRNAs
  kfold_obj_loop <- kfold_obj %>%
    mutate(cutoffs_90_10 = map(train, ~ quantile(.x$C0, c(0.1, 0.9))),
           cutoffs_80_20 = map(train, ~ quantile(.x$C0, c(0.2, 0.8))),
           cutoffs_66_33 = map(train, ~ quantile(.x$C0, c(0.33, 0.67))),
           cutoffs_50_50 = map(train, ~ quantile(.x$C0, c(0.5, 0.5))),
           eff_mat0 = map2(train, cutoffs_90_10,
                           ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = i)),
           ineff_mat0 = map2(train, cutoffs_90_10,
                             ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = i)),
           eff_mat1 = map2(train, cutoffs_80_20,
                           ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = i)),
           ineff_mat1 = map2(train, cutoffs_80_20,
                             ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = i)),
           eff_mat2 = map2(train, cutoffs_66_33,
                           ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = i)),
           ineff_mat2 = map2(train, cutoffs_66_33,
                             ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = i)),
           eff_mat3 = map2(train, cutoffs_50_50,
                           ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = i)),
           ineff_mat3 = map2(train, cutoffs_50_50,
                             ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = i)),
           ratio_mat0 = map2(eff_mat0, ineff_mat0, ~ map2(.x, .y, `-`)),
           ratio_mat1 = map2(eff_mat1, ineff_mat1, ~ map2(.x, .y, `-`)),
           ratio_mat2 = map2(eff_mat2, ineff_mat2, ~ map2(.x, .y, `-`)),
           ratio_mat3 = map2(eff_mat3, ineff_mat3, ~ map2(.x, .y, `-`)),
           train_ratio_score_0 = map2(train, ratio_mat0, pssm_sum_score),
           train_ratio_score_1 = map2(train, ratio_mat1, pssm_sum_score),
           train_ratio_score_2 = map2(train, ratio_mat2, pssm_sum_score),
           train_ratio_score_3 = map2(train, ratio_mat3, pssm_sum_score),
           test_ratio_score_0 = map2(test, ratio_mat0, pssm_sum_score),
           test_ratio_score_1 = map2(test, ratio_mat1, pssm_sum_score),
           test_ratio_score_2 = map2(test, ratio_mat2, pssm_sum_score),
           test_ratio_score_3 = map2(test, ratio_mat3, pssm_sum_score),
           train = pmap(list(train, train_ratio_score_0, train_ratio_score_1, train_ratio_score_2, train_ratio_score_3),
                        ~ bind_cols(..1, data.frame(ratio_score_0 = ..2,
                                                    ratio_score_1 = ..3,
                                                    ratio_score_2 = ..4,
                                                    ratio_score_3 = ..5))),
           test = pmap(list(test, test_ratio_score_0, test_ratio_score_1, test_ratio_score_2, test_ratio_score_3),
                       ~ bind_cols(..1, data.frame(ratio_score_0 = ..2,
                                                   ratio_score_1 = ..3,
                                                   ratio_score_2 = ..4,
                                                   ratio_score_3 = ..5))))
  #Calculate mean Spearman correlation across folds
  # ratio_cutoff_comparison <- kfold_obj_loop %>%
  #   mutate(markov_ratio_spearman = map(test,
  #                                      ~ data.frame(r0_sc = cor(.x$C0, .x$ratio_score_0, method = "spearman"),
  #                                                   r1_sc = cor(.x$C0, .x$ratio_score_1, method = "spearman"),
  #                                                   r2_sc = cor(.x$C0, .x$ratio_score_2, method = "spearman"),
  #                                                   r3_sc = cor(.x$C0, .x$ratio_score_3, method = "spearman")))) %>%
  #   pull(markov_ratio_spearman) %>%
  #   bind_rows() %>%
  #   summarize(avg0 = mean(r0_sc),
  #             avg1 = mean(r1_sc),
  #             avg2 = mean(r2_sc),
  #             avg3 = mean(r3_sc),
  #             sd0 = sd(r0_sc),
  #             sd1 = sd(r1_sc),
  #             sd2 = sd(r2_sc),
  #             sd3 = sd(r3_sc))
  
  #Calculate mean Pearson correlation across folds
  ratio_cutoff_comparison <- kfold_obj_loop %>%
    mutate(markov_ratio_pearson = map(test,
                                      ~ data.frame(r0_pc = cor(.x$C0, .x$ratio_score_0, method = "pearson"),
                                                   r1_pc = cor(.x$C0, .x$ratio_score_1, method = "pearson"),
                                                   r2_pc = cor(.x$C0, .x$ratio_score_2, method = "pearson"),
                                                   r3_pc = cor(.x$C0, .x$ratio_score_3, method = "pearson")))) %>%
    pull(markov_ratio_pearson) %>%
    bind_rows() %>%
    summarize(avg0 = mean(r0_pc),
              avg1 = mean(r1_pc),
              avg2 = mean(r2_pc),
              avg3 = mean(r3_pc),
              sd0 = sd(r0_pc),
              sd1 = sd(r1_pc),
              sd2 = sd(r2_pc),
              sd3 = sd(r3_pc))
  
  #Gather results
  # ratio_cutoff_comparison <- bind_cols(cutoff = c("q90/10", "q80/20", "q67/33", "q50/50"),
  #           gather(ratio_cutoff_comparison[,1:4], value = "avg_spearman"),
  #           gather(ratio_cutoff_comparison[,5:8], value = "sd")) %>%
  #   select(-`key...2`, -`key...4`) %>%
  #   mutate(order = i)
  
  ratio_cutoff_comparison <- bind_cols(cutoff = c("q90/10", "q80/20", "q67/33", "q50/50"),
                                       gather(ratio_cutoff_comparison[,1:4], value = "avg_pearson"),
                                       gather(ratio_cutoff_comparison[,5:8], value = "sd")) %>%
    select(-`key...2`, -`key...4`) %>%
    mutate(order = i)
  
  likelihood_ratio_outcomes[[i]] <- ratio_cutoff_comparison
  
}
```



```{r}
likelihood_ratio_outcomes_combined<- likelihood_ratio_outcomes %>%
  bind_rows()

head(likelihood_ratio_outcomes_combined)

# likelihood_ratio_outcomes_combined_display <- likelihood_ratio_outcomes_combined %>%
#   select(order, cutoff, avg_spearman, sd) %>%
#   arrange(order, cutoff) %>%
#   mutate(avg_spearman = round(avg_spearman, 4),
#          sd = round(sd, 4))

likelihood_ratio_outcomes_combined_display <- likelihood_ratio_outcomes_combined %>%
  select(order, cutoff, avg_pearson, sd) %>%
  arrange(order, cutoff) %>%
  mutate(avg_pearson = round(avg_pearson, 4),
         sd = round(sd, 4))

# Add optimal ratio to kfold obj
# kfold_obj <- kfold_obj %>%
#   mutate(cutoffs_67_33 = map(train, ~ quantile(.x$C0, c(0.33, 0.67))),
#          eff_mat2 = map2(train, cutoffs_67_33,
#                          ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = 1)),
#          ineff_mat2 = map2(train, cutoffs_67_33,
#                            ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = 1)),
#          ratio_mat2 = map2(eff_mat2, ineff_mat2, ~ map2(.x, .y, `-`)),
#          train_ratio_score_2 = map2(train, ratio_mat2, pssm_sum_score),
#          test_ratio_score_2 = map2(test, ratio_mat2, pssm_sum_score),
#          train = pmap(list(train, train_ratio_score_2),
#                       ~ bind_cols(..1, data.frame(ratio_score_2nd = ..2))),
#          test = pmap(list(test, test_ratio_score_2),
#                      ~ bind_cols(..1, data.frame(ratio_score_2nd = ..2))))

kfold_obj <- kfold_obj %>%
  mutate(cutoffs_80_20 = map(train, ~ quantile(.x$C0, c(0.2, 0.8))),
         eff_mat2 = map2(train, cutoffs_80_20,
                         ~ position_specific_score_matrices(.x[.x$C0 > .y[2],], order = 2)),
         ineff_mat2 = map2(train, cutoffs_80_20,
                           ~ position_specific_score_matrices(.x[.x$C0 < .y[1],], order = 2)),
         ratio_mat2 = map2(eff_mat2, ineff_mat2, ~ map2(.x, .y, `-`)),
         train_ratio_score_2 = map2(train, ratio_mat2, pssm_sum_score),
         test_ratio_score_2 = map2(test, ratio_mat2, pssm_sum_score),
         train = pmap(list(train, train_ratio_score_2),
                      ~ bind_cols(..1, data.frame(ratio_score_2nd = ..2))),
         test = pmap(list(test, test_ratio_score_2),
                     ~ bind_cols(..1, data.frame(ratio_score_2nd = ..2))))

#Save kfold object with ratios
saveRDS(kfold_obj, "data/Created/train-10-fold-ratio.rds")
```
